version: 2

project_name: docker-dns-sync

builds:
  - id: docker-dns-sync
    main: ./cmd/docker-dns-sync
    binary: docker-dns-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: release-archives
    ids:
      - docker-dns-sync
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: true
